# Generated by Django 5.0.7 on 2024-08-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_memberapplication_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplication',
            name='library_branch',
        ),
    ]
