# Generated by Django 5.0.7 on 2024-08-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('membership', '0003_remove_memberapplication_library_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='library_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='library.librarybranch'),
            preserve_default=False,
        ),
    ]
