# Generated by Django 4.2.4 on 2023-09-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_birth_registration_profile_nid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
