# Generated by Django 5.0.7 on 2024-08-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_memberapplication_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberapplication',
            options={'verbose_name': 'Member Application', 'verbose_name_plural': 'Member Applications'},
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
