# Generated by Django 5.0.7 on 2024-08-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_memberapplication_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
