# Generated by Django 5.0.7 on 2024-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
