# Generated by Django 5.0.7 on 2024-08-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_memberapplication_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberapplication',
            old_name='feedback',
            new_name='reject_feedback',
        ),
    ]
