# Generated by Django 5.0.7 on 2024-08-14 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_memberapplication_birth_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='birth_registration',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='phone',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_date', models.DateField(auto_now_add=True)),
                ('membership_type', models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium')], default='Regular', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('nid', models.CharField(blank=True, max_length=17, unique=True)),
                ('birth_registration', models.CharField(blank=True, max_length=100, unique=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
