# Generated by Django 5.0.7 on 2024-08-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_memberapplication_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
