# Generated by Django 5.0.7 on 2024-08-14 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_user_username'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='library_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='library.librarybranch'),
            preserve_default=False,
        ),
    ]
