# Generated by Django 5.0.7 on 2024-08-15 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_member_library_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberapplication',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_application', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
