# Generated by Django 5.0.7 on 2024-08-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_memberapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='membership_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium')], default='Regular', max_length=50),
        ),
    ]
