# Generated by Django 5.0.7 on 2024-08-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_memberapplication_membership_type'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='library_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_applications', to='library.librarybranch'),
            preserve_default=False,
        ),
    ]
