# Generated by Django 5.0.7 on 2024-08-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_memberapplication_library_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_type', models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium')], default='Regular', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='library_branch',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='library_branch',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='user',
        ),
    ]
