# Generated by Django 5.0.7 on 2024-08-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_membership_remove_member_library_branch_and_more'),
        ('book', '0002_alter_borrowing_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberApplication',
        ),
    ]
