# Generated by Django 5.0.7 on 2024-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_available_copies_book_total_copies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='library_branch',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
